name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ macos-15-intel, macos-26 ]
        include:
          - os: ubuntu-latest
            container: ghcr.io/homebrew/brew:main
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          core: true

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Check formula and cask style
        run: brew style Formula Casks

      - name: Check GitHub Actions workflows
        if: matrix.os == 'ubuntu-latest'
        run: brew style .github/workflows/tests.yml .github/workflows/publish.yml

      - name: Read formulae and casks on all platforms
        run: brew readall --aliases --os=all --arch=all oiekjr/tap

      - name: Audit formulae and casks
        run: brew audit --except=installed --tap=oiekjr/tap

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
